apiVersion: apps/v1
kind: Deployment
metadata:
  name: flag-service
  labels:
    app: flag-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flag-service
  template:
    metadata:
      labels:
        app: flag-service
    spec:
      containers:
      - name: flag-service
        # É ESSA LINHA AQUI QUE O NOSSO ROBÔ VAI ATUALIZAR SOZINHO:
        image: 515747005528.dkr.ecr.us-east-1.amazonaws.com/testeflagservice:5a03868d9b1f150f264cae6e3d1119164a58abd2
        ports:
        - containerPort: 5000