apiVersion: apps/v1
kind: Deployment
metadata:
  name: flag-service
  labels:
    app: flag-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flag-service
  template:
    metadata:
      labels:
        app: flag-service
    spec:
      containers:
      - name: flag-service
        # É ESSA LINHA AQUI QUE O NOSSO ROBÔ VAI ATUALIZAR SOZINHO:
        image: 515747005528.dkr.ecr.us-east-1.amazonaws.com/testeflagservice:fa52b8922c6bd79fbe07c6497be04981e9ac116f
        ports:
        - containerPort: 5000